AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Agent OmniRetail on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11

Resources:
  OmniRetailSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: agent-omniretail-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH

  OmniRetailApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: agent-omniretail-api
      Handler: app.lambda_handler.lambda_handler
      CodeUri: .
      Policies:
        - S3ReadPolicy:
            BucketName: agent-omniretail-data-526680396747
        - DynamoDBCrudPolicy:
            TableName: agent-omniretail-sessions
      Events:
        ChatApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post
      Environment:
        Variables:
          APP_ENV: aws
          DATA_BUCKET: agent-omniretail-data-526680396747
          SESSIONS_TABLE: agent-omniretail-sessions

Outputs:
  OmniRetailApiUrl:
    Description: URL base del endpoint del agente
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat"
